name = "MLJNaiveBayesInterface"
uuid = "33e4bacb-b9e2-458e-9a13-5d9a90b235fa"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.1.5"

[deps]
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
NaiveBayes = "9bbee03b-0db5-5f46-924f-b5c9c21b8c60"

[compat]
LogExpFunctions = "0.2, 0.3"
MLJModelInterface = "0.3.5, 0.4, 1"
NaiveBayes = "^0.5.0"
julia = "^1.3"

[extras]
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["MLJBase", "StableRNGs", "Test"]
